### ISSUE TITLE
How to resolve FileNotFoundError: [Errno 2] No such file or directory: 'models/vggish_pca_params.npz'

### ISSUE THREAD

**Issue by akshaychavakula** [devicehive/devicehive-audio-analysis#19]
Hello,

I am getting this error while trying to run the code via command line on Ubuntu. I use the command `python3 parse_file.py Recording_5.wav` 

Here is the Traceback:  

Traceback (most recent call last):
  File "parse_file.py", line 39, in <module>
    process_file(**vars(args))
  File "parse_file.py", line 31, in process_file
    with WavProcessor() as proc:
  File "/home/akshay/devicehive-audio-analysis/audio/processor.py", line 40, in __init__
    pca_params = np.load(params.VGGISH_PCA_PARAMS)
  File "/home/akshay/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'models/vggish_pca_params.npz'

**Comment by akshaychavakula** [comment]
Error Resolved. Use `wget https://s3.amazonaws.com/audioanalysis/models.tar.gz`  and
`tar -xzf models.tar.gz` to download and extract models to source directory
